# Generated by Django 3.0.5 on 2020-05-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20200501_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('join_confirmation', 'Join Confirmation'), ('host_confirmation', 'Host Confirmation'), ('join', 'Join')], max_length=255, verbose_name='Type')),
                ('language_code', models.CharField(max_length=255, verbose_name='Language Code')),
                ('subject_template', models.CharField(max_length=255, verbose_name='Subject Template')),
                ('body_template', models.TextField(verbose_name='Body Template')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
