# Generated by Django 3.0.5 on 2020-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_auto_20200502_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='body_template',
            field=models.TextField(help_text='Body text of the email to be sent. The Variable {{ event }} and its children {{ event.start }}, {{ event.join_url }} etc. can be used.', verbose_name='Body Template'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='language_code',
            field=models.CharField(default='en', max_length=255, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject_template',
            field=models.CharField(help_text='Subject of the email to be sent. The Variable {{ event }} and its children {{ event.start }} etc. can be used.', max_length=255, verbose_name='Subject Template'),
        ),
    ]
