# Generated by Django 3.0.5 on 2020-05-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_auto_20200502_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
