# Generated by Django 3.0.5 on 2020-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0007_event_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], default='en', max_length=2, verbose_name='Language'),
        ),
    ]
