# Generated by Django 3.0.6 on 2020-05-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0009_auto_20200505_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailtemplate',
            name='language_code',
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='body_template_de',
            field=models.TextField(help_text='Body text of the email to be sent. The Variable {{ event }} and its children {{ event.start }}, {{ event.join_url }} etc. can be used.', null=True, verbose_name='Body Template'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='body_template_en',
            field=models.TextField(help_text='Body text of the email to be sent. The Variable {{ event }} and its children {{ event.start }}, {{ event.join_url }} etc. can be used.', null=True, verbose_name='Body Template'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='subject_template_de',
            field=models.CharField(help_text='Subject of the email to be sent. The Variable {{ event }} and its children {{ event.start }} etc. can be used.', max_length=255, null=True, verbose_name='Subject Template'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='subject_template_en',
            field=models.CharField(help_text='Subject of the email to be sent. The Variable {{ event }} and its children {{ event.start }} etc. can be used.', max_length=255, null=True, verbose_name='Subject Template'),
        ),
    ]
