# Generated by Django 3.0.6 on 2020-05-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0010_auto_20200505_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start',), 'verbose_name': 'Circle', 'verbose_name_plural': 'Circles'},
        ),
        migrations.AlterModelOptions(
            name='mailtemplate',
            options={'ordering': ('type',), 'verbose_name': 'MailTemplate', 'verbose_name_plural': 'MailTemplates'},
        ),
    ]
