# Generated by Django 3.0.6 on 2020-05-06 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("circles", "0011_auto_20200506_1325"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailtemplate",
            name="body_template",
            field=models.TextField(
                help_text="Body text of the email to be sent. The Variable {{ event }} and its children {{ event.start }}, {{ event.join_url }}, {{ event.delete_url }} etc. can be used.",
                verbose_name="Body Template",
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="body_template_de",
            field=models.TextField(
                help_text="Body text of the email to be sent. The Variable {{ event }} and its children {{ event.start }}, {{ event.join_url }}, {{ event.delete_url }} etc. can be used.",
                null=True,
                verbose_name="Body Template",
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="body_template_en",
            field=models.TextField(
                help_text="Body text of the email to be sent. The Variable {{ event }} and its children {{ event.start }}, {{ event.join_url }}, {{ event.delete_url }} etc. can be used.",
                null=True,
                verbose_name="Body Template",
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("join_confirmation", "Join Confirmation"),
                    ("host_confirmation", "Host Confirmation"),
                    ("join", "Join"),
                    ("deleted", "Circle deleted Notification"),
                ],
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
