# Generated by Django 3.0.6 on 2020-05-06 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0015_auto_20200506_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='circles.Participation', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
