# Generated by Django 3.0.6 on 2020-05-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='headline_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='headline_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Headline'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='text_de',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_de',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
