# Generated by Django 3.0.6 on 2020-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_simplepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplepage',
            name='text_de',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='simplepage',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
    ]
